In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
import re
import joblib
import string

In [7]:
fake = pd.read_csv("Fake.csv")
true = pd.read_csv("True.csv")

In [8]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [9]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [10]:
fake["class"] = 0
true["class"] = 1

In [11]:
data = pd.concat([fake, true], axis=0)

In [12]:
data.sample(10)

,title,text,subject,date,class
3388,Stephen King BLASTS Republicans Cozying Up To...,Vladimir Putin s name used to be mud with the ...,News,"December 16, 2016",0
7693,Trump Bails On CPAC And Republicans Are Now B...,It looks as though the man most likely to get ...,News,"March 4, 2016",0
19310,MEDIA ATTACKS TAYLOR SWIFT Over Refusal To Cri...,Tom Barnes mocks Taylor Swift in his latest ar...,left-news,"Jan 14, 2017",0
6398,Here’s Why Conservatives Are Silent About 201...,Police in this country had a great run. Let s ...,News,"May 13, 2016",0
3112,Exclusive: Trump administration eyes hardening...,WASHINGTON (Reuters) - President Donald Trump’...,politicsNews,"June 20, 2017",1
15326,EU states see Britain failing to meet Brexit d...,BRUSSELS (Reuters) - EU envoys discussed on We...,worldnews,"November 8, 2017",1
2825,"Senior U.S., Russian diplomats to meet in Wash...",WASHINGTON (Reuters) - U.S. Undersecretary of ...,politicsNews,"July 11, 2017",1
16178,SENIOR CIA INTEL: “Wiretapping of Trump Transi...,,Government News,"Mar 27, 2017",0
3320,Comey account could fuel obstruction accusatio...,NEW YORK (Reuters) - Former FBI Director James...,politicsNews,"June 8, 2017",1
8289,Organizers name TV journalists to moderate U.S...,"WASHINGTON (Reuters) - Journalists from NBC, A...",politicsNews,"September 2, 2016",1

In [13]:
data = data.drop(["title", "subject", "date"], axis=1)

In [14]:
data.reset_index(inplace=True)

In [15]:
data.drop(['index'],axis = 1,inplace=True)

In [16]:
data.sample(5)

                                                    text  class
15602  No need to file rules don t apply to Obama s a...      0
2281   It can easily be said that Donald Trump doesn ...      0
31340  SAN FRANCISCO (Reuters) - Facebook Inc (FB.O) ...      1
29316  TOKYO (Reuters) - Japan is hammering out plans...      1
26635  WASHINGTON (Reuters) - U.S. President Donald T...      1

In [ ]:
def clean_text(text):
    text = text.lower()
    text = re.sub('\[.*?\]',"",text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()